### PR TITLE
Fix auto-publish

### PR DESCRIPTION
**Pull request by marcoscaceres**
[Auto-publishing is currently failing](https://lists.w3.org/Archives/Public/public-tr-notifications/2017Jul/0046.html) because it thinks you are trying to republish the document as a Working Draft. You should continue to make non-normative changes to this spec, and publish them as CR. 

Otherwise, if you are making substantive changes to the spec (that would warrant dropping back to WD), you might want to disable auto publishing entirely.

### CODE REVIEW

**Comment by igrigorik** [comment]
LGTM. @siusin can you sanity check?

**Comment by siusin** [comment]
I don't think the auto-pub system can handle a living CR document... /cc @deniak @plehegar 

We can either make the changes in the editor's draft, and add them to the /TR version when we move to Proposed REC, or publish a FPWD of performance-timeline-3 and maintain the changes in the L3 WDs.

**Comment by deniak** [comment]
True, the system can only handle some WDs and Notes for now. Republishing a CR needs to go to webreq.

**Comment by marcoscaceres** [comment]
Hmmm, can we get that fixed? As long as the process is followed, there is no reason to not allow CR to automatically publish.

**Comment by deniak** [comment]
Yes, the goal is to add more types of documents such as CRs and FPWDs but it's a bit tricky as there are other systems involved (IPP, comm announcement, etc) for these. So it's in the todo list but we just need to find time to work on the implementations.

**Comment by igrigorik** [comment]
@siusin @plehegar bump. Any guidance here? Can we land this? If not, should we close this?

**Comment by siusin** [comment]
Not much progress on Level-2 because it's still in CR, but we can auto-pub the WDs of Level-3 once the group make the decision to publish a FPWD.

**Comment by igrigorik** [comment]
Since we're still actively iterating on L2.. Closing this, we can revisit once we have L3 FPWD.

**Pull request closed without merging**
