### PR TITLE
Case sensitivity for getEntries

### PR DESCRIPTION
**Pull request by plehegar**
Proposal for #57

### CODE REVIEW

**Comment by yoavweiss** [comment]
Is this PR still open? (since you reverted the change)

**Comment by plehegar** [comment]
yes. I made the mistake to do the commit on the main branch and had to revert but this PR still stands.

**Comment by yoavweiss** [comment]
OK, so if we want to review, we should review https://github.com/w3c/performance-timeline/pull/58/commits/33578f2dc78a39ea0a7f7cf6ac1abdc10765b930 directly?

Assuming we agree on names being insensitive and values being sensitive (which seems rather confusing to me, but *shrug*), the patch looks good.

**Comment by plehegar** [comment]
[Don't merge this PR until we get confirmation we want it. See https://www.w3.org/2016/09/14-webperf-minutes.html#item03 ]

**Comment by plehegar** [comment]
This is ready for review and merge. Matches discussion at https://www.w3.org/2016/09/22-webperf-minutes.html#item06

**Comment by plehegar** [comment]
Review the test at
https://github.com/w3c/web-platform-tests/pull/3833

**Comment by igrigorik** [comment]
@plehegar thanks! The tests look good. Also, LGTM for spec change. Merging.

**Pull request merged**
