### PR TITLE
Expose everywhere

### PR DESCRIPTION
**Pull request by Ms2ger**
Ref: https://github.com/tc39/proposal-shadowrealm/issues/331

***
<a href="https://pr-preview.s3.amazonaws.com/Igalia/performance-timeline/pull/193.html" title="Last updated on Nov 25, 2021, 2:48 PM UTC (f95c32d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/193/ca6936d...Igalia:f95c32d.html" title="Last updated on Nov 25, 2021, 2:48 PM UTC (f95c32d)">Diff</a>

### CODE REVIEW

**Comment by npm1** [comment]
Seems reasonable, seems to be blocked on the WebIDL change. The Web Perf WG has TPAC discussions next week, hopefully the implications of this are discussed to ensure all relevant members are good with this.

**Comment by marcoscaceres** [comment]
@Ms2ger, could you kindly please rebase?

**Comment by Ms2ger** [comment]
Done, thanks for the reminder!

**Review by marcoscaceres — APPROVED** [review]

**Comment by Ms2ger** [comment]
This should be ready to merge now; I'll submit tests to WPT once the IDL changes have propagated from webref.

**Pull request merged**
