### PR TITLE
Remove dependencies section

### LINKED ISSUE #106: Is the "Dependencies" section relevant?
It seems like the [Dependencies](https://w3c.github.io/performance-timeline/#dependencies) section is out of date, and I'm not sure it's necessary.
I couldn't find any dependency on PerformanceResourceTiming and initiatorType even though they are listed there. I'm guessing we had such a dependency, but it's no longer there.

Otherwise, can't we simply make sure that any dependency is properly linked, and delete this entire section?

@igrigorik - WDYT?

### PR DESCRIPTION
**Pull request by yoavweiss**
Closes #106

***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/performance-timeline/pull/107.html" title="Last updated on Oct 9, 2018, 11:28 AM GMT (14ac04e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/107/81a6242...yoavweiss:14ac04e.html" title="Last updated on Oct 9, 2018, 11:28 AM GMT (14ac04e)">Diff</a>

### CODE REVIEW

**Comment by siusin** [comment]
We'll need to update the inline anchors if we remove this section, f.ex., 

`<a>context object</a>` -> `<a data-cite="!WHATWG-DOM#context-object">context object</a>`

otherwise the linking magic of ReSpec won't work.

**Comment by yoavweiss** [comment]
Added inline links to all the removed references. Landing.

**Comment by npm1** [comment]
I think this PR has broken two links:
* Link to the Performance interface in the WebIDL description in 3.1
* Link to "Queue a task" in 4.1

**Comment by yoavweiss** [comment]
@npm1 Thanks for catching that! Fixed at https://github.com/w3c/performance-timeline/pull/109
Can you review?

**Pull request merged**
